language: node_js
node_js:
- "8.9.1"
cache: pip
before_install:
- npm i -g npm@latest
- npm install -g @angular/cli
install:
- npm i
script:
- ng build --prod --aot --vendor-chunk --common-chunk --delete-output-path --build-optimizer
before_deploy:
- pip install awscli --user
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: airswapchat.com
  region: $AWS_DEFAULT_REGION
  skip_cleanup: true
  acl: public_read
  local-dir: dist/
  on:
    branch: master
after_deploy:
- aws configure set preview.cloudfront true
- aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
